### PR TITLE
Exit with the error on unsupported bitops schema data type in fail_fast mode

### PR DESCRIPTION
**Pull request by PhillypHenning**
# Description

Small update to the exit logic for fail fast usage, this is to properly support our Github Action usage

## Type of change

- [X] Bug fix (non-breaking change which fixes an issue)

# How Has This Been Tested?
Tested locally

**Logs**

# Checklist:

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have made corresponding changes to the documentation

### CODE REVIEW

**Review by armab — COMMENTED** [review]
The PR title will need better detail as we're generating Release notes based on those.
> Exit with the error code on unsupported type in bitops schema.

as I have zero context, ^^ is that accurate?


Is there perhaps an example or logs that may highlight the bug we're fixing in this PR?

**Comment by mickmcgrath13** [comment]
This PR should probably fix a bug with exiting in `run_cmd`.

I’m not convinced the exception is being raised..
Might need to use `pipe.returncode` after `pipe.communicate`

more context:
pipeline is using bitops 2.2.1:
https://github.com/bitovi/devops-training-ec2-gha-example/actions/runs/3639474356/jobs/6143060556#step:2:240
Pipeline should have failed here ([before script](https://github.com/bitovi/github-actions-deploy-docker-to-ec2/blob/bitops-2.2/operations/deployment/terraform/bitops.before-deploy.d/create-tf-state-bucket.sh#L5)):
https://github.com/bitovi/devops-training-ec2-gha-example/actions/runs/3639474356/jobs/6143060556#step:2:760
before script calls `run_cmd`:
https://github.com/bitovi/bitops/blob/5b0fec06e6f74c9aa5d1e63509215859ec230f82/scripts/plugins/utilities.py#L342
run_cmd check `BITOPS_fast_fail_mode`:
https://github.com/bitovi/bitops/blob/5b0fec06e6f74c9aa5d1e63509215859ec230f82/scripts/plugins/utilities.py#L374

**Comment by mickmcgrath13** [comment]
need this:
```
process.communicate()
process_return_code = process.returncode
if process_return_code = 0:
  print("yay")
else:
  logger.error("not yay")
  sys.exit(101)
```

**Comment by armab** [comment]
@mickmcgrath13 That bug fix is in the https://github.com/bitovi/bitops/pull/373 PR.

**Review by armab — APPROVED** [review]

**Pull request merged**
