### PR TITLE
Added handling for Ansible extra-vars options

### PR DESCRIPTION
**Pull request by dylan-bitovi**
I've done some testing using this with the ST2 Ansible deployment+a modified BitOps image and it seems to operate correctly.

I can pass in vars directly or load from a json file as described in the docs, both work:
https://docs.ansible.com/ansible/latest/user_guide/playbooks_variables.html#defining-variables-at-runtime

### CODE REVIEW

**Comment by mickmcgrath13** [comment]
@dylan-bitovi Nice!!

Please update the docs, too:
https://github.com/bitovi/bitops/blob/master/docs/tool-configuration/configuration-ansible.md

**Comment by dylan-bitovi** [comment]
BitOps docs have been updated to include extra_vars.

**Review by mickmcgrath13 — CHANGES_REQUESTED** [review]
Add an example up here, too, please:
https://github.com/bitovi/bitops/pull/38/files#diff-bf10fa4a9431c5525dd255c48a2464930f85d6eda7edb38874ad5ed88b82e9cbR12

**Review by mickmcgrath13 — APPROVED** [review]
LGTM: Merge when ready

**Pull request merged**
